#!/usr/bin/python3
""" factorizes all numbers in a file """
from sys import argv
from math import sqrt

def factorize(number):
    """ factorizes a number """
    if number % 2 == 0:
        num = number // 2
        print(f"{number}={num}*2")

    sqn = int(sqrt(number))
    if sqn % 2 == 0:
        sqn += 1

    for i in range(3, sqn + 1, 2):
        if number % i == 0:
            num = number // i
            print(f"{number}={num}*{i}")
            break
    if number % i != 0:
        print(f"{number}={number}*1")


def factorize_in_a_file(file_path):
    """ Factorizes numbers in a file """
    results = []
    with open(file_path, 'r') as file:
        for line in file:
            try:
                number = int(line)
                factors = factorize(number)
            except ValueError:
                pass

    return results

if __name__ == "__main__":
    if len(argv) < 2:
        print("Please provide a file path")
    else:
        file_path = argv[1]
        factored_results = factorize_in_a_file(file_path)
